#!/usr/bin/env python3
"""Project the current goal and its task cursor into .goals/focus.md.

The focus file is the executor's first read in every new thread: it names the
goal to work on now, shows the contract's declarative outcome tree with live
checkmarks, and ends with the exact commands that advance the cursor. It is a
REGENERATED PROJECTION — the locked contract is the source of truth, verifier
evidence is the oracle, and task marks are progress bookkeeping for
cross-thread continuity, never achievement. Subcommands: (bare)/show
regenerates, `done <id>...` / `undo <id>...` move the cursor and regenerate.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

from campaign_status import derive_status
from common import (
    child_contract_path,
    contract_lock_status,
    flatten_task_tree,
    git_root_or_cwd,
    goals_relative,
    infer_campaign_manifest,
    load_task_state,
    parse_campaign_children,
    parse_sections,
    parse_task_tree,
    save_task_state,
    split_goal_id_title,
)


def _contract_goal_id(contract: Path) -> str:
    try:
        head = contract.read_text(encoding="utf-8").splitlines()[:1]
    except OSError:
        return "current"
    if head:
        m = re.search(r"\bG-\d+\b", head[0])
        if m:
            return m.group(0)
    return "current"


def resolve_goal(root: Path, goal_override: str | None = None) -> dict:
    """Which goal the cursor points at: campaign next_child when a campaign
    lock exists (the chain's advance/stop authority stays campaign_status),
    else the single root contract."""
    goals = root / ".goals"
    out: dict = {"root": str(root), "mode": "single", "warnings": [], "chain_note": None,
                 "position": None, "goal_id": None, "contract": None, "error": None}
    if (goals / "campaign.sha256").exists():
        manifest, reason = infer_campaign_manifest(goals)
        if manifest is None:
            out["error"] = reason
            return out
        out["mode"] = "campaign"
        out["manifest"] = str(manifest)
        status = derive_status(manifest)
        out["warnings"].extend(status.get("warnings", []))
        children = parse_campaign_children(manifest.read_text(encoding="utf-8"))
        by_id = {c["id"]: c for c in children}
        gid = goal_override or status.get("next_child")
        if status.get("chain_should_stop") and not goal_override:
            out["chain_note"] = status.get("stop_reason")
        out["position"] = (f"{status.get('achieved_pending_audit', 0)}/{status.get('ready_total', 0)} "
                           "goals achieved (pending audit) in this wave")
        if gid and gid in by_id:
            out["goal_id"] = gid
            out["title"] = by_id[gid].get("title", "")
            out["contract"] = child_contract_path(manifest, by_id[gid])
        elif goal_override:
            out["error"] = f"Unknown goal id {goal_override}; campaign children: {', '.join(sorted(by_id))}"
        return out
    contract = goals / "current.md"
    if not contract.exists():
        out["error"] = "No mission found: .goals/current.md does not exist and no campaign is locked."
        return out
    out["goal_id"] = goal_override or _contract_goal_id(contract)
    out["contract"] = contract
    raw_title = contract.read_text(encoding="utf-8").splitlines()[0]
    _, title = split_goal_id_title(re.sub(r"^#\s*Goal Contract:\s*", "", raw_title))
    out["title"] = title
    return out


def _render_tree(nodes: list, done: dict, lines: list) -> None:
    for node in nodes:
        mark = "x" if node["id"] in done else " "
        lines.append(f"{'  ' * node['depth']}- [{mark}] {node['id']} {node['text']}")
        _render_tree(node["children"], done, lines)


def build_focus(root: Path, goal_override: str | None = None) -> dict:
    info = resolve_goal(root, goal_override)
    if info.get("error"):
        return info
    contract: Path | None = info.get("contract")
    lines = [
        "# Focus (derived view — never authoritative)",
        "",
        "> Regenerated by focus.py. The locked contract is the source of truth and",
        "> the verifier is the oracle; task marks are a progress cursor, never",
        "> achievement. Do not edit this file by hand — move the cursor with the",
        "> commands at the bottom.",
        "",
    ]
    if contract is None or not contract.exists():
        if info["mode"] == "campaign":
            lines.append(f"- Campaign: {goals_relative(Path(info['manifest']))} — {info['position']}")
        if info.get("chain_note"):
            lines.append(f"- Chain note: {info['chain_note']}")
        lines += ["", "No current goal contract to focus on; see the chain note above."]
        info["text"] = "\n".join(lines) + "\n"
        return info

    text = contract.read_text(encoding="utf-8")
    sections = parse_sections(text)
    ls = contract_lock_status(contract)
    lock_word = "locked" if ls.get("matched") else ("LOCK MISMATCH" if ls.get("locked") else "not locked")
    lines.append(f"- Goal: {info['goal_id']} — {info.get('title', '')}")
    lines.append(f"- Contract: {goals_relative(contract)} (sha256 {ls.get('current_hash', '')[:16]}… — {lock_word})")
    if info["mode"] == "campaign":
        lines.append(f"- Campaign: {goals_relative(Path(info['manifest']))} — {info['position']}")
    if info.get("chain_note"):
        lines.append(f"- Chain note: {info['chain_note']}")

    objective = sections.get("Objective", "").strip()
    if objective:
        lines += ["", "## Objective", "", objective]
    intent = sections.get("Intent", "").strip()
    if intent:
        lines += ["", "## Intent", "", intent]

    tree = parse_task_tree(sections.get("Tasks", ""))
    done, warns = load_task_state(root, info["goal_id"], contract)
    info["warnings"].extend(warns)
    all_nodes = flatten_task_tree(tree)
    done_n = sum(1 for n in all_nodes if n["id"] in done)
    lines += ["", "## Tasks (declarative outcomes — cursor state)", ""]
    if tree:
        _render_tree(tree, done, lines)
        lines += ["", f"{len(all_nodes) - done_n} of {len(all_nodes)} outcomes open."]
    else:
        lines += ["(The contract declares no ## Tasks tree; work from its Terminal State clauses.)"]
    for w in info["warnings"]:
        lines.append(f"- WARN: {w}")

    ref = goals_relative(contract)
    if info["mode"] == "campaign":
        evdir = f".goals/evidence/children/{info['goal_id']}/verifiers"
    else:
        evdir = ".goals/evidence/verifiers"
    report = f".goals/reports/{info['goal_id']}-report.md"
    lines += [
        "",
        "## Working this goal",
        "",
        "Open-world discovery first: re-verify the workspace's current state against the",
        "contract's assumptions and anchors — context may have drifted since authoring.",
        "Closed-world execution: any approach satisfying the contract within scope and",
        "budget is valid; discoveries beyond scope become Follow-Up Candidates in the",
        "report, never new work.",
        "",
        f"- Mark an outcome satisfied: `python3 .goals/bin/focus.py done <id>` (e.g. `done 1.2 1.3`; `undo <id>` reverses; marking outcomes is bookkeeping, not achievement)",
        f"- When every outcome is satisfied: run `python3 .goals/bin/run_verifiers.py {ref} --run --evidence-dir {evdir}`, write the report at {report} with the required headings, then run `python3 .goals/bin/focus.py` — it will surface what is next.",
    ]
    info["text"] = "\n".join(lines) + "\n"
    info["tasks_total"] = len(all_nodes)
    info["tasks_done"] = done_n
    info["tree_ids"] = [n["id"] for n in all_nodes]
    return info


def write_focus(root: Path, info: dict) -> Path:
    path = root / ".goals" / "focus.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(info["text"], encoding="utf-8")
    return path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("verb", nargs="?", default="show", choices=["show", "done", "undo"],
                        help="show (default): regenerate .goals/focus.md; done/undo: move the task cursor, then regenerate.")
    parser.add_argument("task_ids", nargs="*", help="Task ids for done/undo, e.g. 1.2 1.3")
    parser.add_argument("--goal", default=None, help="Campaign child id to focus instead of the derived next goal.")
    parser.add_argument("--root", default=None, help="Workspace root (default: git root or cwd).")
    parser.add_argument("--no-write", action="store_true", help="Do not write .goals/focus.md (print only).")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()
    root = Path(args.root).resolve() if args.root else git_root_or_cwd()

    if args.verb in {"done", "undo"}:
        if not args.task_ids:
            print(f"focus {args.verb}: pass at least one task id (e.g. 1.2).", file=sys.stderr)
            return 2
        info = build_focus(root, args.goal)
        if info.get("error"):
            print(info["error"], file=sys.stderr)
            return 2
        valid = set(info.get("tree_ids", []))
        unknown = [t for t in args.task_ids if t not in valid]
        if unknown:
            print(f"focus {args.verb}: unknown task id(s) {', '.join(unknown)} for {info['goal_id']}; "
                  f"valid ids: {', '.join(info.get('tree_ids', [])) or '(no ## Tasks tree)'}", file=sys.stderr)
            return 2
        contract = Path(info["contract"])
        done, _ = load_task_state(root, info["goal_id"], contract)
        from datetime import datetime, timezone
        stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        for t in args.task_ids:
            if args.verb == "done":
                done[t] = stamp
            else:
                done.pop(t, None)
        save_task_state(root, info["goal_id"], contract, done)
        info = build_focus(root, args.goal)  # re-derive with the new cursor

    else:
        info = build_focus(root, args.goal)
        if info.get("error"):
            print(info["error"], file=sys.stderr)
            return 2

    if not args.no_write:
        info["focus_file"] = str(write_focus(root, info))
    if args.json:
        out = {k: (str(v) if isinstance(v, Path) else v) for k, v in info.items() if k != "text"}
        print(json.dumps(out, indent=2, ensure_ascii=False))
    else:
        print(info["text"], end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
