# Generated by project-harness. Review before editing.
# project-harness: managed-file
# These recipes assume a POSIX shell. On Windows, use Git Bash or WSL.
# Usage examples:
#   just bootstrap         # install local prerequisites and tooling
#   just ci                # run the pull-request verification surface
#   just build -- --help   # pass extra flags through to the underlying build tool

set shell := ["bash", "-euo", "pipefail", "-c"]

# Show the recipe catalog and short descriptions
default:
    @just --list

__GUIDANCE_BLOCK__
__VARIABLES__
__COMPONENT_BLOCKS__
__BUILD_BLOCK__
__RELEASE_BLOCK__
__TEST_BLOCK__
__LINT_BLOCK__
__FMT_BLOCK__
__FMT_CHECK_BLOCK__
__CI_BLOCK__
__HOOKS_BLOCK__
__CLEAN_BLOCK__
__BOOTSTRAP_BLOCK__
__DEV_BLOCK__
__DOCKER_BLOCK__
