# Generated by project-harness for a local-dist pattern.
# dist/ stays ignored.
# project-harness: managed-file
# These recipes assume a POSIX shell. On Windows, use Git Bash or WSL.

set shell := ["bash", "-euo", "pipefail", "-c"]

default:
    @just --list

__GUIDANCE_BLOCK__
__VARIABLES__
__COMPONENT_BLOCKS__
__DIST_VARIABLES__
__BUILD_BLOCK__
__RELEASE_BLOCK__
__DIST_BLOCK__
__TEST_BLOCK__
__LINT_BLOCK__
__FMT_BLOCK__
__FMT_CHECK_BLOCK__
__CI_BLOCK__
__CLEAN_BLOCK__
__BOOTSTRAP_BLOCK__
__DEV_BLOCK__
__DOCKER_BLOCK__
