# BEGIN project-harness managed gitattributes
# Generated by project-harness. Review before editing.
# project-harness: managed-section
* text=auto eol=lf

# Project Harness inserts the generated baseline near the top of .gitattributes
# so later repo-specific rules can override these broad defaults.
# END project-harness managed gitattributes
