import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm, mkdir } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { pathToFileURL } from 'node:url';
import os from 'node:os';
import path from 'node:path';
import { createEvidenceRun } from '../../../plugins/playwright-testing/runtime/evidence.mjs';
import { renderGallery } from '../../../plugins/playwright-testing/runtime/gallery.mjs';
import { capture } from '../../../plugins/playwright-testing/runtime/capture.mjs';

const runtime = process.env.PW_TEST_PLAYWRIGHT_PATH;
test('portable gallery supports offline search, pagination, original context, mobile layout and keyboard access', { skip: !runtime, timeout: 90000 }, async t => {
  const require = createRequire(import.meta.url);
  const playwright = require(runtime);
  if (process.env.PW_TEST_EVIDENCE_BROWSER_OUTPUT) await mkdir(process.env.PW_TEST_EVIDENCE_BROWSER_OUTPUT, { recursive: true });
  const root = await mkdtemp(path.join(process.env.PW_TEST_EVIDENCE_BROWSER_OUTPUT || os.tmpdir(), 'pw-gallery-'));
  if (!process.env.PW_TEST_EVIDENCE_BROWSER_OUTPUT) t.after(() => rm(root, { recursive: true, force: true }));
  await mkdir(root, { recursive: true });
  const run = await createEvidenceRun({ outputDir: path.join(root, 'run') });
  const browser = await playwright.chromium.launch({ headless: true, channel: 'chromium', chromiumSandbox: true });
  t.after(() => browser.close());
  const fixture = await browser.newPage();
  await fixture.setContent('<!doctype html><main style="font:24px system-ui;padding:40px;color:#173040;background:#e6f5f1"><h1>Original capture</h1><p>Every observation retains its context.</p></main>');
  const blob = await run.storeBlob(await fixture.screenshot(), { extension: 'png' });
  await fixture.close();
  const dangerous = '</script><img src=x onerror="globalThis.attacked=true">';
  for (let i = 0; i < 50; i++) await run.record({ id: `observation-${i}`, type: 'capture', label: i === 0 ? dangerous : `State ${i}`, state: { url: `https://example.org/page?index=${i}#preserved`, viewport: { width: 390, height: 844 }, scheme: 'dark' }, images: [blob], rationale: `Original context ${i} 🦄` });
  await run.enqueue({ id: 'remaining', journey: ['Start', 'Open menu'] });
  await run.record({ type: 'transition', from: 'observation-0', to: 'observation-1', action: 'Navigate' });
  await run.finish(); await run.close();
  const gallery = await renderGallery(run.outputDir);
  const context = await browser.newContext({ viewport: { width: 1440, height: 950 } });
  const page = await context.newPage();
  const errors = [], externalRequests = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  page.on('request', request => { if (/^https?:/.test(request.url())) externalRequests.push(request.url()); });
  await page.goto(pathToFileURL(gallery.indexPath).href);
  await page.getByRole('status').filter({ hasText: '50 matching captures' }).waitFor();
  assert.equal(await page.locator('article.card').count(), 24);
  assert.equal(await page.evaluate(() => globalThis.attacked), undefined);
  await page.getByRole('button', { name: 'Next', exact: true }).click();
  assert.equal(await page.locator('#page-number').innerText(), '2 / 3');
  assert.equal(await page.evaluate(() => document.activeElement.id), 'results');
  await page.getByLabel('Search', { exact: true }).fill(dangerous);
  assert.equal(await page.locator('article.card').count(), 1);
  assert.ok(await page.getByRole('link', { name: dangerous, exact: true }).isVisible());
  await page.getByRole('link', { name: 'Reproduction and full context', exact: true }).click();
  await page.getByRole('heading', { name: 'Reproduction and original context' }).waitFor();
  assert.match(await page.locator('pre').innerText(), /Original context 0 🦄/);
  await page.getByLabel('Show images at original pixel size').check();
  await page.waitForFunction(() => [...document.querySelectorAll('img')].every(image => image.complete && image.naturalWidth > 0));
  assert.equal(await page.locator('img').evaluate(image => image.clientWidth === image.naturalWidth), true);
  assert.equal(await page.evaluate(() => globalThis.attacked), undefined);
  await page.getByRole('link', { name: '← Evidence gallery' }).click();
  await page.getByRole('status').waitFor();
  await page.getByText('Observed transitions', { exact: true }).click();
  assert.equal(await page.locator('#transition-map svg').count(), 1);
  await page.getByText('Observed transitions', { exact: true }).click();
  await page.getByRole('button', { name: 'Change appearance' }).click();
  assert.equal(await page.locator('html').getAttribute('data-appearance'), 'light');
  await page.screenshot({ path: path.join(root, 'desktop.png') });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.waitForFunction(() => document.documentElement.scrollWidth <= innerWidth + 1, undefined, { timeout: 2000 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.getByLabel('Search', { exact: true }).fill('State 49');
  assert.equal(await page.locator('article.card').count(), 1);
  await page.screenshot({ path: path.join(root, 'mobile.png') });
  await page.locator('img').first().scrollIntoViewIfNeeded();
  await page.waitForFunction(() => [...document.querySelectorAll('article img')].every(image => image.complete && image.naturalWidth > 0));
  assert.deepEqual(errors, []); assert.deepEqual(externalRequests, []);
  await context.close();
  t.diagnostic(JSON.stringify({ browser: browser.version(), gallery: gallery.indexPath, offlineRequests: externalRequests.length, errors: errors.length, desktop: [1440, 950], mobile: [390, 844] }));
});


test('appearance filter consumes real capture observations across light and dark contexts', { skip: !runtime, timeout: 90000 }, async t => {
  const require = createRequire(import.meta.url), playwright = require(runtime);
  const parent = process.env.PW_TEST_EVIDENCE_BROWSER_OUTPUT || os.tmpdir(); await mkdir(parent, { recursive: true });
  const root = await mkdtemp(path.join(parent, 'observed-appearance-'));
  if (!process.env.PW_TEST_EVIDENCE_BROWSER_OUTPUT) t.after(() => rm(root, { recursive: true, force: true }));
  const run = await createEvidenceRun({ outputDir: path.join(root, 'run') });
  const browser = await playwright.chromium.launch({ headless: true, channel: 'chromium', chromiumSandbox: true });
  t.after(() => browser.close());
  const observed = [];
  for (const colorScheme of ['dark', 'light']) {
    const context = await browser.newContext({ colorScheme, viewport: { width: 740, height: 500 } });
    const page = await context.newPage();
    await page.setContent('<!doctype html><main><h1>Appearance fixture</h1><p>The capture adapter records the observed preference.</p></main>');
    const record = await capture(page, { run, id: `actual-${colorScheme}`, label: `Actual ${colorScheme} context`, state: { requestedAppearance: colorScheme } });
    assert.equal(record.state.observedPreferences.colorScheme, colorScheme);
    assert.equal(record.state.scheme, undefined); assert.equal(record.state.colorScheme, undefined);
    observed.push(record.state.observedPreferences);
    await context.close();
  }
  await run.finish(); await run.close();
  const gallery = await renderGallery(run.outputDir);
  const page = await browser.newPage({ viewport: { width: 1000, height: 800 } });
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto(pathToFileURL(gallery.indexPath).href);
  await page.getByRole('status').filter({ hasText: '2 matching captures' }).waitFor();
  const options = await page.locator('#scheme option').allTextContents();
  assert.deepEqual(options, ['All appearances', 'dark', 'light']);
  for (const colorScheme of ['dark', 'light']) {
    await page.getByLabel('Appearance', { exact: true }).selectOption(colorScheme);
    assert.equal(await page.locator('article.card').count(), 1);
    assert.ok(await page.getByRole('link', { name: `Actual ${colorScheme} context`, exact: true }).isVisible());
  }
  await page.screenshot({ path: path.join(root, 'observed-appearance.png') });
  assert.deepEqual(errors, []); await page.close();
  t.diagnostic(JSON.stringify({ root, observed, appearanceOptions: options, filteredCaptureCount: 1 }));
});
