import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, rm, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { createRequire } from 'node:module';
import { createEvidenceRun } from '../../../plugins/playwright-testing/runtime/evidence.mjs';
import { renderGallery } from '../../../plugins/playwright-testing/runtime/gallery.mjs';

const runtime=process.env.PW_TEST_PLAYWRIGHT_PATH;
test('mixed journals open on useful capture previews while supporting records stay searchable and compact', {skip:!runtime,timeout:60000}, async t=>{
  const parent=process.env.PW_TEST_GALLERY_OUTPUT||tmpdir();await mkdir(parent,{recursive:true});
  const root=await mkdtemp(path.join(parent,'gallery-reading-'));
  if(!process.env.PW_TEST_GALLERY_OUTPUT)t.after(()=>rm(root,{recursive:true,force:true}));
  const {chromium}=createRequire(import.meta.url)(runtime);
  const browser=await chromium.launch({headless:true,channel:'chromium',chromiumSandbox:true});t.after(()=>browser.close());
  const context=await browser.newContext({viewport:{width:1124,height:900},colorScheme:'dark'});
  const page=await context.newPage();
  const run=await createEvidenceRun({outputDir:path.join(root,'run')});
  const frames=[];
  for(const [index,color] of ['#195a86','#71512b','#17765e'].entries()){
    await page.setContent(`<main style="height:700px;background:${color};color:white;font:32px system-ui;padding:35px"><h1>Scroll frame ${index+1}</h1><p>Full image remains readable.</p></main>`);
    frames.push(await run.storeBlob(await page.screenshot(),{mime:'image/png',extension:'png'}));
  }
  await run.record({id:'capture-sequence',type:'capture',label:'Full schedule across three frames',status:'complete',state:{viewport:{width:1124,height:900},scheme:'dark'},images:frames});
  await run.record({id:'capture-detail',type:'capture',label:'Selected detail',status:'complete',images:[frames[0]]});
  const recordId='7966d8fb-ea59-4517-a70d-821b59661917';
  await run.record({id:recordId,type:'session-detail-check',message:'The selected session matches its row.'});
  for(let i=0;i<40;i++)await run.record({type:'discovery',note:`Supporting observation ${i}`});
  await run.record({id:'failed-capture',type:'capture',label:'Capture interrupted before screenshot',status:'partial',images:[],warnings:[{message:'Target disappeared'}]});
  await run.finish();await run.close();
  const originalJournal=await readFile(path.join(run.outputDir,'observations.ndjson'));
  const gallery=await renderGallery(run.outputDir);
  await context.setOffline(true);
  const errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))external.push(r.url())});
  await page.goto(pathToFileURL(gallery.indexPath).href);
  await page.getByRole('status').filter({hasText:'3 matching captures'}).waitFor();
  assert.equal(await page.locator('article.card').count(),3);
  assert.equal(await page.locator('.observation-row').count(),0);
  assert.ok(!(await page.locator('#results').innerText()).includes('Unspecified'));
  assert.ok(!(await page.locator('#results').innerText()).includes(recordId));
  assert.ok(await page.getByText('No image was retained.',{exact:false}).isVisible(),'Incomplete captures remain visible in the primary view.');
  const sequence=page.locator('article.card').filter({has:page.getByRole('link',{name:'Full schedule across three frames',exact:true})});
  assert.equal(await sequence.locator('img').count(),1,'The sequence keeps one useful preview instead of shrinking every frame into columns.');
  await sequence.locator('img').evaluate(img=>img.decode());
  const before=await sequence.boundingBox(),imageBounds=await sequence.locator('img').boundingBox();
  assert.ok(imageBounds.width>before.width*.9);
  const first=await sequence.locator('img').getAttribute('src');
  await sequence.getByRole('button',{name:'Next image for Full schedule across three frames',exact:true}).click();
  await sequence.locator('img').evaluate(img=>img.decode());
  assert.notEqual(await sequence.locator('img').getAttribute('src'),first);
  assert.equal(await sequence.locator('.frame-navigation span').textContent(),'2 / 3');
  const after=await sequence.boundingBox();assert.ok(Math.abs(before.height-after.height)<1,'Frame navigation does not resize the surrounding card.');
  assert.match(await sequence.locator('.image-preview').getAttribute('href'),/#image-2$/);
  await page.screenshot({path:path.join(root,'captures-desktop.png')});
  await sequence.locator('.image-preview').click();
  await page.locator('#image-2 img').evaluate(img=>img.decode());
  assert.ok((await page.locator('#image-2 img').getAttribute('src')).endsWith(frames[1].path));
  await page.getByRole('link',{name:'← Evidence gallery',exact:true}).click();
  await page.getByLabel('Search',{exact:true}).fill(recordId);
  await page.getByRole('button',{name:'Search supporting records (1 match)',exact:true}).click();
  assert.equal(await page.locator('.observation-row').count(),1);
  assert.equal(await page.locator('article.card').count(),0);
  assert.ok(await page.getByRole('link',{name:'Session detail check 1',exact:true}).isVisible());
  assert.ok(!(await page.locator('#results').innerText()).includes('Unspecified'));
  await page.getByRole('link',{name:'Open record: Session detail check 1',exact:true}).click();
  assert.ok((await page.locator('pre').textContent()).includes(recordId),'Original identity stays available at the record boundary.');
  await page.getByRole('link',{name:'← Evidence gallery',exact:true}).click();
  const supporting=page.getByRole('button',{name:'Supporting records (41)',exact:true});await supporting.focus();await page.keyboard.press('Enter');
  const rows=await page.locator('.observation-row').evaluateAll(nodes=>nodes.map(n=>{const r=n.getBoundingClientRect();return {top:r.top,bottom:r.bottom}}));
  assert.equal(rows.length,24);
  for(let i=1;i<rows.length;i++)assert.ok(rows[i].top-rows[i-1].bottom<2,'Supporting records flow as compact adjacent rows.');
  await page.screenshot({path:path.join(root,'supporting-desktop.png')});
  await page.getByRole('button',{name:'Next',exact:true}).click();assert.equal(await page.locator('.observation-row').count(),17);
  await page.getByRole('button',{name:'Captures (3)',exact:true}).click();
  await page.setViewportSize({width:390,height:844});
  await page.waitForFunction(() => document.documentElement.scrollWidth <= innerWidth + 1, undefined, { timeout: 2000 });
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
  await page.locator('article.card').first().scrollIntoViewIfNeeded();
  await page.screenshot({path:path.join(root,'captures-phone.png')});
  assert.deepEqual(await readFile(path.join(run.outputDir,'observations.ndjson')),originalJournal);
  assert.deepEqual(errors,[]);assert.deepEqual(external,[]);
  const recordsOnly=await createEvidenceRun({outputDir:path.join(root,'records-only')});
  await recordsOnly.record({type:'custom-note',message:'A collection can contain useful records without screenshots.'});
  await recordsOnly.finish();await recordsOnly.close();
  const recordsGallery=await renderGallery(recordsOnly.outputDir);
  await page.goto(pathToFileURL(recordsGallery.indexPath).href);
  await page.getByRole('status').filter({hasText:'1 matching record'}).waitFor();
  assert.ok(await page.getByText('A collection can contain useful records without screenshots.',{exact:true}).isVisible());
  assert.equal(await page.locator('.observation-row').count(),1);
  t.diagnostic(`Native reading regressions: ${root}`);
});
