#!/usr/bin/env bash
set -euo pipefail

# install-hooks.sh - Install managed Git hooks for gitops-workflow.
#
# Usage:
#   bash scripts/install-hooks.sh [--repo <path>] [--force]
#
# Behavior:
# - Installs a managed pre-commit hook that runs sensitive-scan.sh.
# - Refuses to overwrite non-managed hook unless --force is provided.

EXIT_SETUP=2
MANAGED_MARKER="gitops-workflow-managed-pre-commit:v1"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
SKILL_ROOT="$(cd "$SCRIPT_DIR/.." && pwd -P)"

REPO_PATH="$(pwd -P)"
FORCE="false"
JSON="false"

print_help() {
  cat <<'USAGE'
Usage:
  bash scripts/install-hooks.sh [--repo <path>] [--force] [--json]

Options:
  --repo <path>   Target git repository path (default: current directory)
  --force         Overwrite existing non-managed pre-commit hook
  --json          Emit machine-readable JSON on success
  -h, --help      Show this help text
USAGE
}

emit_result() {
  local status="$1"
  local repo="$2"
  local hook_path="$3"
  local force="$4"
  if [[ "$JSON" == "true" ]]; then
    python3 - "$status" "$repo" "$hook_path" "$force" <<'PY'
import json
import sys

print(json.dumps({
    "status": sys.argv[1],
    "repo": sys.argv[2],
    "hook_path": sys.argv[3],
    "force": sys.argv[4] == "true",
}))
PY
  else
    echo "Installed managed pre-commit hook at: $hook_path"
  fi
}

die() {
  echo "Error: $1" >&2
  exit "${2:-1}"
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "missing required command: $1" "$EXIT_SETUP"
}

require_opt_value() {
  local opt="$1"
  local val="${2:-}"
  if [[ -z "$val" || "$val" == --* ]]; then
    die "option '$opt' requires a value" "$EXIT_SETUP"
  fi
}

is_managed_hook() {
  local hook_path="$1"
  [[ -f "$hook_path" ]] || return 1
  grep -Fxq "# $MANAGED_MARKER" "$hook_path" || return 1
  grep -Fxq "# Generated by gitops-workflow install-hooks.sh" "$hook_path" || return 1
  grep -Fxq 'bash "$SKILL_ROOT/scripts/sensitive-scan.sh" --staged --redact --repo "$REPO_ROOT"' "$hook_path" || return 1
  return 0
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo)
      require_opt_value "--repo" "${2:-}"
      REPO_PATH="${2:-}"
      shift 2
      ;;
    --force)
      FORCE="true"
      shift
      ;;
    --json)
      JSON="true"
      shift
      ;;
    -h|--help)
      print_help
      exit 0
      ;;
    *)
      die "unknown argument: $1" "$EXIT_SETUP"
      ;;
  esac
done

[[ -n "$REPO_PATH" ]] || die "--repo path is empty" "$EXIT_SETUP"
require_cmd git

if ! git -C "$REPO_PATH" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  die "--repo is not a git repository: $REPO_PATH" "$EXIT_SETUP"
fi

HOOK_PATH_RAW="$(git -C "$REPO_PATH" rev-parse --git-path hooks/pre-commit)"
if [[ "$HOOK_PATH_RAW" = /* ]]; then
  HOOK_PATH="$HOOK_PATH_RAW"
else
  HOOK_PATH="$REPO_PATH/$HOOK_PATH_RAW"
fi
mkdir -p "$(dirname "$HOOK_PATH")"

if [[ -f "$HOOK_PATH" ]] && ! is_managed_hook "$HOOK_PATH"; then
  if [[ "$FORCE" != "true" ]]; then
    die "existing pre-commit hook is not managed by gitops-workflow; rerun with --force to replace" "$EXIT_SETUP"
  fi
fi

printf -v SKILL_ROOT_ESCAPED '%q' "$SKILL_ROOT"

cat > "$HOOK_PATH" <<EOF_HOOK
#!/usr/bin/env bash
set -euo pipefail
# $MANAGED_MARKER
# Generated by gitops-workflow install-hooks.sh

SKILL_ROOT=$SKILL_ROOT_ESCAPED

if [[ ! -x "\$SKILL_ROOT/scripts/sensitive-scan.sh" ]]; then
  echo "Error: missing scanner script at \$SKILL_ROOT/scripts/sensitive-scan.sh" >&2
  exit 2
fi

REPO_ROOT="\$(git rev-parse --show-toplevel)"
bash "\$SKILL_ROOT/scripts/sensitive-scan.sh" --staged --redact --repo "\$REPO_ROOT"
EOF_HOOK

chmod +x "$HOOK_PATH"

emit_result "installed" "$REPO_PATH" "$HOOK_PATH" "$FORCE"
