//! Golden pipeline integration tests for deterministic compose/swarm workflows.

use std::fs;
use std::panic::{catch_unwind, AssertUnwindSafe};
use std::path::{Path, PathBuf};

use architect_core::cache;
use architect_core::extract;
use architect_core::generator::{self, AnchorMode};
use architect_core::heuristics::DeployMode;
use architect_core::policy::{self, PolicyDomain, RuleSeverity};

const SNAPSHOT_HEADER: &str = "# AUTO-GENERATED by golden_pipeline.rs. Do not edit manually.";

#[derive(Debug, Clone)]
struct GoldenCase {
    name: &'static str,
    input: &'static str,
    cache_dir: &'static str,
    policy: &'static str,
    mode: DeployMode,
    expected_violation_substrings: &'static [&'static str],
    expected_violation_rule_ids: &'static [&'static str],
    required_patch_ops: &'static [&'static str],
    forbidden_patch_ops: &'static [&'static str],
    expected_warn_rule_ids: &'static [&'static str],
    allowed_remaining_violation_rule_ids: &'static [&'static str],
    expected_patch_plan: &'static str,
    expected_hardened: &'static str,
    expected_anchored: &'static str,
}

#[derive(Debug, Clone)]
struct DockerfileGoldenCase {
    name: &'static str,
    input: &'static str,
    cache_dir: Option<&'static str>,
    policy: &'static str,
    required_violation_rule_ids: &'static [&'static str],
    forbidden_patch_rule_ids: &'static [&'static str],
    expected_patch_plan: &'static str,
    expected_hardened: &'static str,
    allowed_remaining_patch_rule_ids: &'static [&'static str],
    allowed_remaining_violation_rule_ids: &'static [&'static str],
}

#[test]
fn compose_and_swarm_golden_pipeline_remains_deterministic() {
    let mut failures = Vec::new();
    for case in golden_cases() {
        if let Err(payload) = catch_unwind(AssertUnwindSafe(|| run_case(&case))) {
            failures.push(format!(
                "{}: {}",
                case.name,
                panic_payload_to_string(payload)
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "compose/swarm golden failures:\n\n{}",
        failures.join("\n\n")
    );
}

#[test]
fn dockerfile_golden_pipeline_remains_deterministic() {
    let mut failures = Vec::new();
    for case in dockerfile_golden_cases() {
        if let Err(payload) = catch_unwind(AssertUnwindSafe(|| run_dockerfile_case(&case))) {
            failures.push(format!(
                "{}: {}",
                case.name,
                panic_payload_to_string(payload)
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "dockerfile golden failures:\n\n{}",
        failures.join("\n\n")
    );
}

#[test]
fn compose_init_perms_hardened_fixture_is_idempotent_under_full_enforcing_policy() {
    let hardened_path =
        fixture_path("tests/golden/compose_init_perms_named_volume/expected.hardened.yaml");
    let cache_path =
        fixture_path("tests/golden/compose_init_perms_named_volume/cache/image-profiles.json");
    let policy_path = references_path("policy-compose-enforcing.yaml");

    let hardened = fs::read_to_string(&hardened_path).expect("hardened fixture should be readable");
    let cache_payload =
        cache::read_cache(&cache_path).expect("golden fixture cache should parse successfully");
    let policy_pack = policy::load_policy_pack(&policy_path, PolicyDomain::Compose)
        .expect("compose enforcing policy should compile");

    let reevaluated = policy::evaluate_compose_policy_with_mode(
        &hardened,
        &cache_payload,
        &policy_pack,
        DeployMode::Compose,
    )
    .expect("policy re-evaluation should succeed");
    assert!(
        reevaluated.violations.is_empty(),
        "hardened init-perms fixture should produce no violations under full enforcing policy"
    );
    assert!(
        reevaluated.patch_plan.is_empty(),
        "hardened init-perms fixture should produce no additional patches under full enforcing policy"
    );
}

#[test]
fn text_golden_snapshots_include_auto_generated_header() {
    for case in golden_cases() {
        assert_snapshot_header(&fixture_path(case.expected_hardened));
        assert_snapshot_header(&fixture_path(case.expected_anchored));
    }
    for case in dockerfile_golden_cases() {
        // Dockerfile patch-plan snapshots are JSON and intentionally do not include text headers.
        assert_snapshot_header(&fixture_path(case.expected_hardened));
    }
}

fn run_case(case: &GoldenCase) {
    let input_path = fixture_path(case.input);
    let cache_dir = fixture_path(case.cache_dir);
    let policy_path = references_path(case.policy);
    let patch_snapshot_path = fixture_path(case.expected_patch_plan);
    let hardened_snapshot_path = fixture_path(case.expected_hardened);
    let anchored_snapshot_path = fixture_path(case.expected_anchored);

    let input_content =
        fs::read_to_string(&input_path).expect("golden fixture input should be readable");
    let extracted = extract::extract_image_sets(&input_content)
        .expect("extract should parse deterministic image references");
    assert!(
        !extracted.valid.is_empty(),
        "fixture {} should contain image references",
        case.name
    );
    assert!(
        extracted.unresolved.is_empty(),
        "fixture {} should not contain unresolved image references",
        case.name
    );

    let cache_path = cache_dir.join("image-profiles.json");
    let cache_payload =
        cache::read_cache(&cache_path).expect("golden fixture cache should parse successfully");
    let policy_pack = policy::load_policy_pack(&policy_path, PolicyDomain::Compose)
        .expect("golden fixture policy should compile");
    for rule_id in case.expected_warn_rule_ids {
        let rule = policy_pack
            .rules
            .iter()
            .find(|rule| rule.id == *rule_id)
            .unwrap_or_else(|| panic!("fixture {} missing policy rule `{}`", case.name, rule_id));
        assert!(
            matches!(rule.severity, RuleSeverity::Warn),
            "fixture {} expected `{}` severity warn in policy pack",
            case.name,
            rule_id
        );
    }

    let initial = policy::evaluate_compose_policy_with_mode(
        &input_content,
        &cache_payload,
        &policy_pack,
        case.mode,
    )
    .expect("initial policy evaluation should succeed");

    for expected in case.expected_violation_substrings {
        assert!(
            initial
                .violations
                .iter()
                .any(|violation| violation.reason.contains(expected)),
            "fixture {} expected violation containing `{}`",
            case.name,
            expected
        );
    }
    let mut actual_violation_rule_ids: Vec<&str> = initial
        .violations
        .iter()
        .map(|item| item.rule_id.as_str())
        .collect();
    actual_violation_rule_ids.sort_unstable();
    let mut expected_violation_rule_ids: Vec<&str> = case.expected_violation_rule_ids.to_vec();
    expected_violation_rule_ids.sort_unstable();
    assert_eq!(
        actual_violation_rule_ids.len(),
        expected_violation_rule_ids.len(),
        "fixture {} violation count mismatch.\nexpected ids: {:?}\nactual ids: {:?}",
        case.name,
        expected_violation_rule_ids,
        actual_violation_rule_ids
    );
    assert!(
        actual_violation_rule_ids == expected_violation_rule_ids,
        "fixture {} violation rule ids drift.\nexpected: {:?}\nactual: {:?}",
        case.name,
        expected_violation_rule_ids,
        actual_violation_rule_ids
    );
    for op in case.required_patch_ops {
        assert!(
            initial.patch_plan.iter().any(|patch| patch.op == *op),
            "fixture {} expected patch op `{}`",
            case.name,
            op
        );
    }
    for op in case.forbidden_patch_ops {
        assert!(
            !initial.patch_plan.iter().any(|patch| patch.op == *op),
            "fixture {} should not include patch op `{}`",
            case.name,
            op
        );
    }

    let rendered_patch_plan =
        serde_json::to_string_pretty(&initial.patch_plan).expect("patch plan should serialize");
    let expected_patch_plan =
        fs::read_to_string(&patch_snapshot_path).expect("patch plan snapshot should be readable");
    assert!(
        !rendered_patch_plan.trim().is_empty(),
        "fixture {} patch plan must not be empty",
        case.name
    );
    assert_eq!(
        rendered_patch_plan.trim(),
        expected_patch_plan.trim(),
        "patch plan drift for fixture {}",
        case.name
    );

    let hardened = policy::apply_compose_patch_plan(&input_content, &initial.patch_plan, case.mode)
        .expect("compose patch application should succeed");
    let expected_hardened =
        fs::read_to_string(&hardened_snapshot_path).expect("hardened snapshot should be readable");
    let expected_hardened = strip_snapshot_header(&expected_hardened);
    assert!(
        !hardened.trim().is_empty(),
        "fixture {} hardened output must not be empty",
        case.name
    );
    assert_eq!(
        hardened.trim(),
        expected_hardened.trim(),
        "hardened compose drift for fixture {}",
        case.name
    );

    let reevaluated = policy::evaluate_compose_policy_with_mode(
        &hardened,
        &cache_payload,
        &policy_pack,
        case.mode,
    )
    .expect("policy re-evaluation should succeed");
    assert!(
        reevaluated.patch_plan.is_empty(),
        "fixture {} should be idempotent after first hardening apply",
        case.name
    );
    let mut remaining_violation_rule_ids: Vec<&str> = reevaluated
        .violations
        .iter()
        .map(|item| item.rule_id.as_str())
        .collect();
    remaining_violation_rule_ids.sort_unstable();
    let mut allowed_violation_rule_ids: Vec<&str> =
        case.allowed_remaining_violation_rule_ids.to_vec();
    allowed_violation_rule_ids.sort_unstable();
    assert_eq!(
        remaining_violation_rule_ids.len(),
        allowed_violation_rule_ids.len(),
        "fixture {} residual violation count mismatch after hardening.\nexpected ids: {:?}\nactual ids: {:?}",
        case.name,
        allowed_violation_rule_ids,
        remaining_violation_rule_ids
    );
    assert_eq!(
        remaining_violation_rule_ids, allowed_violation_rule_ids,
        "fixture {} residual violation drift after hardening",
        case.name
    );

    let anchored =
        generator::generate_anchored_compose(&hardened, case.mode, AnchorMode::Auto, None)
            .expect("compose anchor generation should succeed");
    let anchored_second =
        generator::generate_anchored_compose(&hardened, case.mode, AnchorMode::Auto, None)
            .expect("repeat anchor generation should succeed");
    assert_eq!(
        anchored, anchored_second,
        "anchor generation should be deterministic for fixture {}",
        case.name
    );

    let expected_anchored =
        fs::read_to_string(&anchored_snapshot_path).expect("anchored snapshot should be readable");
    let expected_anchored = strip_snapshot_header(&expected_anchored);
    assert!(
        !anchored.trim().is_empty(),
        "fixture {} anchored output must not be empty",
        case.name
    );
    assert_eq!(
        anchored.trim(),
        expected_anchored.trim(),
        "anchored compose drift for fixture {}",
        case.name
    );
}

fn run_dockerfile_case(case: &DockerfileGoldenCase) {
    let input_path = fixture_path(case.input);
    let policy_path = references_path(case.policy);
    let patch_snapshot_path = fixture_path(case.expected_patch_plan);
    let cache_payload = case.cache_dir.map(|cache_dir| {
        cache::read_cache(&fixture_path(cache_dir).join("image-profiles.json"))
            .expect("dockerfile fixture cache should parse successfully")
    });

    let input_content =
        fs::read_to_string(&input_path).expect("dockerfile golden fixture should be readable");
    let policy_pack = policy::load_policy_pack(&policy_path, PolicyDomain::Dockerfile)
        .expect("dockerfile golden policy should compile");

    let initial = policy::evaluate_dockerfile_policy_with_cache_and_source(
        &input_content,
        &policy_pack,
        cache_payload.as_ref(),
        Some(&input_path),
    )
    .expect("dockerfile policy evaluation should succeed");

    for rule_id in case.required_violation_rule_ids {
        assert!(
            initial
                .violations
                .iter()
                .any(|violation| violation.rule_id == *rule_id),
            "fixture {} expected violation with rule id `{}`",
            case.name,
            rule_id
        );
    }
    for rule_id in case.forbidden_patch_rule_ids {
        assert!(
            !initial
                .patch_plan
                .iter()
                .any(|patch| patch.rule_id == *rule_id),
            "fixture {} should not auto-patch detect-only rule id `{}`",
            case.name,
            rule_id
        );
    }

    let rendered_patch_plan =
        serde_json::to_string_pretty(&initial.patch_plan).expect("patch plan should serialize");
    let expected_patch_plan =
        fs::read_to_string(&patch_snapshot_path).expect("patch plan snapshot should be readable");
    assert!(
        !rendered_patch_plan.trim().is_empty(),
        "fixture {} dockerfile patch plan must not be empty",
        case.name
    );
    assert_eq!(
        rendered_patch_plan.trim(),
        expected_patch_plan.trim(),
        "dockerfile patch plan drift for fixture {}",
        case.name
    );

    let hardened = policy::apply_dockerfile_patch_plan(&input_content, &initial.patch_plan)
        .expect("dockerfile patch application should succeed");
    let expected_hardened = fs::read_to_string(fixture_path(case.expected_hardened))
        .expect("hardened snapshot readable");
    let expected_hardened = strip_snapshot_header(&expected_hardened);
    assert!(
        !hardened.trim().is_empty(),
        "fixture {} dockerfile hardened output must not be empty",
        case.name
    );
    assert_eq!(
        hardened.trim(),
        expected_hardened.trim(),
        "dockerfile hardened drift for fixture {}",
        case.name
    );
    let reevaluated = policy::evaluate_dockerfile_policy_with_cache_and_source(
        &hardened,
        &policy_pack,
        cache_payload.as_ref(),
        Some(&input_path),
    )
    .expect("dockerfile policy re-evaluation should succeed");
    let mut remaining_rule_ids: Vec<&str> = reevaluated
        .patch_plan
        .iter()
        .map(|patch| patch.rule_id.as_str())
        .collect();
    remaining_rule_ids.sort_unstable();
    let mut allowed_rule_ids: Vec<&str> = case.allowed_remaining_patch_rule_ids.to_vec();
    allowed_rule_ids.sort_unstable();
    assert_eq!(
        remaining_rule_ids.len(),
        allowed_rule_ids.len(),
        "dockerfile residual patch count mismatch for fixture {}.\nexpected ids: {:?}\nactual ids: {:?}",
        case.name,
        allowed_rule_ids,
        remaining_rule_ids
    );
    assert_eq!(
        remaining_rule_ids, allowed_rule_ids,
        "dockerfile residual patch drift for fixture {}",
        case.name
    );
    let mut remaining_violation_rule_ids: Vec<&str> = reevaluated
        .violations
        .iter()
        .map(|item| item.rule_id.as_str())
        .collect();
    remaining_violation_rule_ids.sort_unstable();
    let mut allowed_violation_rule_ids: Vec<&str> =
        case.allowed_remaining_violation_rule_ids.to_vec();
    allowed_violation_rule_ids.sort_unstable();
    assert_eq!(
        remaining_violation_rule_ids.len(),
        allowed_violation_rule_ids.len(),
        "dockerfile residual violation count mismatch for fixture {}.\nexpected ids: {:?}\nactual ids: {:?}",
        case.name,
        allowed_violation_rule_ids,
        remaining_violation_rule_ids
    );
    assert_eq!(
        remaining_violation_rule_ids, allowed_violation_rule_ids,
        "dockerfile residual violation drift for fixture {}",
        case.name
    );
}

fn golden_cases() -> Vec<GoldenCase> {
    vec![
        GoldenCase {
            name: "compose_dual",
            input: "tests/golden/compose_dual/input.compose.yaml",
            cache_dir: "tests/golden/compose_dual/cache",
            policy: "policy-compose-enforcing.yaml",
            mode: DeployMode::Compose,
            expected_violation_substrings: &[],
            expected_violation_rule_ids: &[
                "AC-CMP-CAPDROP",
                "AC-CMP-CAPDROP",
                "AC-CMP-DIGEST",
                "AC-CMP-DIGEST",
                "AC-CMP-HEALTH",
                "AC-CMP-HEALTH",
                "AC-CMP-NNP",
                "AC-CMP-NNP",
                "AC-CMP-READONLY",
                "AC-CMP-READONLY",
                "AC-CMP-RESOURCES",
                "AC-CMP-RESOURCES",
                "AC-CMP-RESOURCES",
                "AC-CMP-RESOURCES",
                "AC-CMP-RESOURCES",
                "AC-CMP-RESOURCES",
                "AC-CMP-RESTART",
                "AC-CMP-RESTART",
                "AC-CMP-WRITABLE",
                "AC-CMP-WRITABLE",
                "AC-CMP-WRITABLE",
                "AC-CMP-WRITABLE",
                "AC-CMP-WRITABLE",
                "AC-CMP-WRITABLE",
            ],
            required_patch_ops: &[],
            forbidden_patch_ops: &[],
            expected_warn_rule_ids: &[],
            allowed_remaining_violation_rule_ids: &[],
            expected_patch_plan: "tests/golden/compose_dual/expected.patch-plan.json",
            expected_hardened: "tests/golden/compose_dual/expected.hardened.yaml",
            expected_anchored: "tests/golden/compose_dual/expected.anchored.yaml",
        },
        GoldenCase {
            name: "swarm_dual",
            input: "tests/golden/swarm_dual/input.stack.yaml",
            cache_dir: "tests/golden/swarm_dual/cache",
            policy: "policy-swarm-enforcing.yaml",
            mode: DeployMode::Swarm,
            expected_violation_substrings: &[],
            expected_violation_rule_ids: &[
                "AC-SWM-CAPDROP",
                "AC-SWM-CAPDROP",
                "AC-SWM-DIGEST",
                "AC-SWM-DIGEST",
                "AC-SWM-HEALTH",
                "AC-SWM-HEALTH",
                "AC-SWM-NNP",
                "AC-SWM-NNP",
                "AC-SWM-READONLY",
                "AC-SWM-READONLY",
                "AC-SWM-RESOURCES",
                "AC-SWM-RESOURCES",
                "AC-SWM-RESOURCES",
                "AC-SWM-RESOURCES",
                "AC-SWM-RESTART",
                "AC-SWM-RESTART",
                "AC-SWM-WRITABLE",
                "AC-SWM-WRITABLE",
                "AC-SWM-WRITABLE",
                "AC-SWM-WRITABLE",
                "AC-SWM-WRITABLE",
                "AC-SWM-WRITABLE",
            ],
            required_patch_ops: &[],
            forbidden_patch_ops: &[],
            expected_warn_rule_ids: &[],
            allowed_remaining_violation_rule_ids: &[],
            expected_patch_plan: "tests/golden/swarm_dual/expected.patch-plan.json",
            expected_hardened: "tests/golden/swarm_dual/expected.hardened.yaml",
            expected_anchored: "tests/golden/swarm_dual/expected.anchored.yaml",
        },
        GoldenCase {
            name: "swarm_balanced",
            input: "tests/golden/swarm_balanced/input.stack.yaml",
            cache_dir: "tests/golden/swarm_balanced/cache",
            policy: "policy-swarm-balanced.yaml",
            mode: DeployMode::Swarm,
            expected_violation_substrings: &[],
            expected_violation_rule_ids: &[
                "AC-SWM-CAPDROP",
                "AC-SWM-CAPDROP",
                "AC-SWM-DIGEST",
                "AC-SWM-DIGEST",
                "AC-SWM-HEALTH",
                "AC-SWM-HEALTH",
                "AC-SWM-NNP",
                "AC-SWM-NNP",
                "AC-SWM-READONLY",
                "AC-SWM-READONLY",
                "AC-SWM-RESOURCES",
                "AC-SWM-RESOURCES",
                "AC-SWM-RESOURCES",
                "AC-SWM-RESOURCES",
                "AC-SWM-RESTART",
                "AC-SWM-RESTART",
                "AC-SWM-WRITABLE",
                "AC-SWM-WRITABLE",
                "AC-SWM-WRITABLE",
                "AC-SWM-WRITABLE",
                "AC-SWM-WRITABLE",
                "AC-SWM-WRITABLE",
            ],
            required_patch_ops: &[],
            forbidden_patch_ops: &[],
            expected_warn_rule_ids: &["AC-SWM-RESTART"],
            allowed_remaining_violation_rule_ids: &[],
            expected_patch_plan: "tests/golden/swarm_balanced/expected.patch-plan.json",
            expected_hardened: "tests/golden/swarm_balanced/expected.hardened.yaml",
            expected_anchored: "tests/golden/swarm_balanced/expected.anchored.yaml",
        },
        GoldenCase {
            name: "compose_init_perms_named_volume",
            input: "tests/golden/compose_init_perms_named_volume/input.compose.yaml",
            cache_dir: "tests/golden/compose_init_perms_named_volume/cache",
            policy: "policy-compose-enforcing.yaml",
            mode: DeployMode::Compose,
            expected_violation_substrings: &[
                "service runs as non-root with writable volumes; init sidecar enforces deterministic ownership",
            ],
            expected_violation_rule_ids: &[
                "AC-CMP-DIGEST",
                "AC-CMP-HEALTH",
                "AC-CMP-PERMS-INIT",
                "AC-CMP-PERMS-INIT",
                "AC-CMP-RESOURCES",
                "AC-CMP-RESOURCES",
                "AC-CMP-RESOURCES",
                "AC-CMP-RESTART",
                "AC-CMP-WRITABLE",
                "AC-CMP-WRITABLE",
                "AC-CMP-WRITABLE",
            ],
            required_patch_ops: &["inject_service", "depends_on_add"],
            forbidden_patch_ops: &[],
            expected_warn_rule_ids: &[],
            allowed_remaining_violation_rule_ids: &[],
            expected_patch_plan:
                "tests/golden/compose_init_perms_named_volume/expected.patch-plan.json",
            expected_hardened:
                "tests/golden/compose_init_perms_named_volume/expected.hardened.yaml",
            expected_anchored:
                "tests/golden/compose_init_perms_named_volume/expected.anchored.yaml",
        },
        GoldenCase {
            name: "compose_bind_mount_skip",
            input: "tests/golden/compose_bind_mount_skip/input.compose.yaml",
            cache_dir: "tests/golden/compose_bind_mount_skip/cache",
            policy: "policy-compose-balanced.yaml",
            mode: DeployMode::Compose,
            expected_violation_substrings: &[
                "bind mount target `/var/cache/app` detected; permission init sidecar chown is disabled by default to avoid host ownership mutation",
            ],
            expected_violation_rule_ids: &[
                "AC-CMP-DIGEST",
                "AC-CMP-HEALTH",
                "AC-CMP-PERMS-INIT",
                "AC-CMP-RESOURCES",
                "AC-CMP-RESOURCES",
                "AC-CMP-RESOURCES",
                "AC-CMP-RESTART",
                "AC-CMP-WRITABLE",
                "AC-CMP-WRITABLE",
                "AC-CMP-WRITABLE",
            ],
            required_patch_ops: &[],
            forbidden_patch_ops: &["inject_service", "depends_on_add"],
            expected_warn_rule_ids: &[],
            allowed_remaining_violation_rule_ids: &["AC-CMP-PERMS-INIT"],
            expected_patch_plan: "tests/golden/compose_bind_mount_skip/expected.patch-plan.json",
            expected_hardened: "tests/golden/compose_bind_mount_skip/expected.hardened.yaml",
            expected_anchored: "tests/golden/compose_bind_mount_skip/expected.anchored.yaml",
        },
        GoldenCase {
            name: "compose_malformed_init_sidecar",
            input: "tests/golden/compose_malformed_init_sidecar/input.compose.yaml",
            cache_dir: "tests/golden/compose_malformed_init_sidecar/cache",
            policy: "policy-compose-enforcing.yaml",
            mode: DeployMode::Compose,
            expected_violation_substrings: &[
                "init-perms sidecar field `image` does not match the canonical contract",
                "init-perms sidecar field `command` does not match the canonical contract",
                "init-perms sidecar field `volumes` does not match the canonical contract",
                "init-perms sidecar field `cap_add` does not match the canonical contract",
                "required init-perms sidecar must not be gated behind profiles",
                "init-perms sidecar field `restart` does not match the canonical contract",
            ],
            expected_violation_rule_ids: &[
                "AC-CMP-DIGEST",
                "AC-CMP-DIGEST",
                "AC-CMP-HEALTH",
                "AC-CMP-PERMS-INIT",
                "AC-CMP-PERMS-INIT",
                "AC-CMP-PERMS-INIT",
                "AC-CMP-PERMS-INIT",
                "AC-CMP-PERMS-INIT",
                "AC-CMP-PERMS-INIT",
                "AC-CMP-RESOURCES",
                "AC-CMP-RESOURCES",
                "AC-CMP-RESOURCES",
                "AC-CMP-RESTART",
                "AC-CMP-WRITABLE",
                "AC-CMP-WRITABLE",
                "AC-CMP-WRITABLE",
            ],
            required_patch_ops: &["remove", "set"],
            forbidden_patch_ops: &["inject_service", "depends_on_add"],
            expected_warn_rule_ids: &[],
            allowed_remaining_violation_rule_ids: &[],
            expected_patch_plan:
                "tests/golden/compose_malformed_init_sidecar/expected.patch-plan.json",
            expected_hardened:
                "tests/golden/compose_malformed_init_sidecar/expected.hardened.yaml",
            expected_anchored:
                "tests/golden/compose_malformed_init_sidecar/expected.anchored.yaml",
        },
    ]
}

fn dockerfile_golden_cases() -> Vec<DockerfileGoldenCase> {
    vec![
        DockerfileGoldenCase {
            name: "dockerfile_balanced",
            input: "tests/golden/dockerfile_balanced/input.Dockerfile",
            cache_dir: None,
            policy: "policy-dockerfile-balanced.yaml",
            required_violation_rule_ids: &[],
            forbidden_patch_rule_ids: &[],
            expected_patch_plan: "tests/golden/dockerfile_balanced/expected.patch-plan.json",
            expected_hardened: "tests/golden/dockerfile_balanced/expected.hardened.Dockerfile",
            allowed_remaining_patch_rule_ids: &[],
            allowed_remaining_violation_rule_ids: &[],
        },
        DockerfileGoldenCase {
            name: "dockerfile_balanced_violations",
            input: "tests/golden/dockerfile_balanced_violations/input.Dockerfile",
            cache_dir: Some("tests/golden/dockerfile_balanced_violations/cache"),
            policy: "policy-dockerfile-balanced.yaml",
            required_violation_rule_ids: &[
                "AC-DF-MULTISTAGE",
                "AC-DF-USER",
                "AC-DF-OCI-LABELS",
                "AC-DF-FROM-DIGEST",
                "AC-DF-REPRODUCIBLE",
                "AC-DF-CACHE-MOUNTS",
                "AC-DF-HEALTHCHECK",
            ],
            forbidden_patch_rule_ids: &["AC-DF-MULTISTAGE", "AC-DF-USER"],
            expected_patch_plan:
                "tests/golden/dockerfile_balanced_violations/expected.patch-plan.json",
            expected_hardened:
                "tests/golden/dockerfile_balanced_violations/expected.hardened.Dockerfile",
            allowed_remaining_patch_rule_ids: &["AC-DF-CACHE-MOUNTS", "AC-DF-HEALTHCHECK"],
            allowed_remaining_violation_rule_ids: &[
                "AC-DF-CACHE-MOUNTS",
                "AC-DF-HEALTHCHECK",
                "AC-DF-MULTISTAGE",
                "AC-DF-USER",
            ],
        },
        DockerfileGoldenCase {
            name: "dockerfile_enforcing",
            input: "tests/golden/dockerfile_enforcing/input.Dockerfile",
            cache_dir: Some("tests/golden/dockerfile_enforcing/cache"),
            policy: "policy-dockerfile-enforcing.yaml",
            required_violation_rule_ids: &[
                "AC-DF-MULTISTAGE",
                "AC-DF-USER",
                "AC-DF-PACKAGE-MGR",
                "AC-DF-OCI-LABELS",
                "AC-DF-FROM-DIGEST",
                "AC-DF-REPRODUCIBLE",
                "AC-DF-CACHE-MOUNTS",
                "AC-DF-SUID-SGID",
                "AC-DF-HEALTHCHECK",
            ],
            forbidden_patch_rule_ids: &["AC-DF-USER", "AC-DF-PACKAGE-MGR"],
            expected_patch_plan: "tests/golden/dockerfile_enforcing/expected.patch-plan.json",
            expected_hardened: "tests/golden/dockerfile_enforcing/expected.hardened.Dockerfile",
            allowed_remaining_patch_rule_ids: &["AC-DF-CACHE-MOUNTS"],
            allowed_remaining_violation_rule_ids: &[
                "AC-DF-CACHE-MOUNTS",
                "AC-DF-HEALTHCHECK",
                "AC-DF-MULTISTAGE",
                "AC-DF-PACKAGE-MGR",
                "AC-DF-USER",
            ],
        },
    ]
}

fn panic_payload_to_string(payload: Box<dyn std::any::Any + Send>) -> String {
    if let Some(message) = payload.downcast_ref::<&str>() {
        return (*message).to_string();
    }
    if let Some(message) = payload.downcast_ref::<String>() {
        return message.clone();
    }
    "non-string panic payload".to_string()
}

fn strip_snapshot_header(snapshot: &str) -> &str {
    if let Some(stripped) = snapshot.strip_prefix(SNAPSHOT_HEADER) {
        if let Some(without_newline) = stripped.strip_prefix('\n') {
            return without_newline;
        }
        if let Some(without_newline) = stripped.strip_prefix("\r\n") {
            return without_newline;
        }
        return stripped;
    }
    snapshot
}

fn assert_snapshot_header(path: &Path) {
    let content = fs::read_to_string(path).unwrap_or_else(|error| {
        panic!("snapshot {} should be readable: {error}", path.display());
    });
    assert!(
        content.starts_with(SNAPSHOT_HEADER),
        "snapshot {} is missing auto-generated header",
        path.display()
    );
}

fn fixture_path(relative: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join(relative)
}

fn references_path(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../plugins/docker-architect/skills/docker-architect/references")
        .join(name)
}
