# AUTO-GENERATED by golden_pipeline.rs. Do not edit manually.
ARG SOURCE_DATE_EPOCH
FROM docker.io/library/debian:12-slim@sha256:cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
LABEL org.opencontainers.image.licenses=unknown
LABEL org.opencontainers.image.revision=unknown
LABEL org.opencontainers.image.source=unknown
RUN apt-get update && apt-get install -y curl
# add --mount=type=cache,target=/var/cache/apt for apt and /usr/local/cargo/registry for cargo
RUN find / -xdev -type f -perm /6000 -exec chmod a-s {} \;
CMD ["bash"]
